project_id = "knjbxqiyngztylnzxzln"

[functions]
[functions.send-reservation-notification]
verify_jwt = false

[functions.confirm-reservation]
verify_jwt = false

[functions.cancel-reservation]
verify_jwt = false

[functions.get-reservation-by-code]
verify_jwt = false